### ISSUE TITLE
VS2012 crashes with last update (installed 08/24)

### ISSUE THREAD

**Issue by hernandezgustavo** [wakatime/visualstudio-wakatime#42] opened 2015-08-26 20:43 UTC
I installed the plugin a time ago and VS2012 noticed me for a new update of the Wakatime plugin. I installed it and I had to disable it because with the latest update VS crashes.

Environment:
- VM running on Mac
- VM specs:
    * Win server 2008 R2 SP1
    * 8GB
    * 2 cores (from i7)
    * VS2012 Pro Update 4

**Comment by alanhamlett** [comment] 2015-08-27 01:37
I've tested with VS2012 Ultimate in Windows 8.1, but not able to reproduce a crash. Can you share the error message from your `ActivityLog.xml`? To have VS write exceptions to that xml log, run VS from a cmd prompt with `devenv /log`. More info [here](http://blogs.msdn.com/b/visualstudio/archive/2010/02/24/troubleshooting-with-the-activity-log.aspx)

**Comment by alanhamlett** [comment] 2016-04-30 12:18
Closing until we have more info.

**Closed by alanhamlett** 2016-04-30 12:18 UTC
Labels: bug
