### ISSUE TITLE
Can't specify proxy

### ISSUE THREAD

**Issue by Marfusios** [wakatime/visualstudio-wakatime#14] opened 2015-05-27 18:49 UTC
Please add support for proxy. Proxy with username and password. Currently this extension throws exception at start if proxy is required.

Maybe some modal dialog, would be great.

**Comment by alanhamlett** [comment] 2015-05-27 19:18
Related to #13 and wakatime/wakatime#23.

**Comment by alanhamlett** [comment] 2015-05-31 01:44
Closing as duplicate of #13

**Closed by alanhamlett** 2015-05-31 01:44 UTC
